#!/bin/bash

source ./lib/colorful

letsencryptDirHost="./data/letsencrypt"
emailArg="--register-unsafely-without-email"


blueecho "1. perform some checks & normalizations ..."
source ./lib/validation

if [ -d "$letsencryptDirHost" ]; then
	orangeecho "creating directory '$letsencryptDirHost' ..."
	mkdir -p "$letsencryptDirHost"
fi

if [ -n "$email" ]; then
	emailArg="--email $email"
fi

echo "Where is the webroot? A directory where certbot stores the token sent by Let's Encrypt and which will be served as a specified path by a web server running on port 80"
read webroot
if [ -z "$webroot" ] && ! [ -d "$webroot" ]; then
	redecho "Invalid input! Either provided an invalid string or the specified directory does not exist"
	exit 1
fi

# modify that line as you like and as required to fit your setup
orangeecho "certbot certonly --webroot \"$webroot\" --config-dir \"$letsencryptDirHost\" -d \"$domain\" $emailArg --rsa-key-size 4096 --agree-to"
echo "Continue executing this [yes|no]:"
read x
if ! [ "$x" = "yes" ]; then
	echo "Aborting ..."
	exit 0
fi

# modify that line as you like and as required to fit your setup
certbot certonly --webroot "$webroot" --config-dir "$letsencryptDirHost" -d "$domain" $emailArg --rsa-key-size 4096 --agree-tos #--force-renewal"
