#!/bin/bash

source ./lib/colorful

usage() {
	blueecho "USAGE 1:"
	blueecho "./add_extension <name of env file> <name of extension>"
	blueecho "./add_extension Bolivia-Cochabamba otp"
	blueecho "USAGE 2 (works only when \$enfile has been set e.g. by 'export $enfile=[...]' or by invoking '. ./workas'):"
	blueecho "./add_extension <name of extension>"
	blueecho "./add_extension otp"
}

envname=""
extname=""

blueecho "1. perform some checks & normalizations"
source ./lib/validation

extname="${args[0]}"
extDir="./extensions/$extname"
## if $extname is empty or $extDir does not exist
if [ -z $extname ] || ! [ -d "$extDir" ]; then
	redecho "  Error: You must specify a valid name of an extension to remove from city '$city'">&2
	echo "  A list of extensions available:"
	dir ./extensions
	exit 1
fi

blueecho "2. remove the extension"

# dataDir="$extDir/data_$city"
# dataDirInactive="$dataDir.inactive"
ymlFile="$extDir/$city.yml"
ymlFileInactive="$ymlFile.inactive"

if [ -f "$ymlFile" ]; then
	orangeecho "   removing extension  '$extname' ( directory '$extDir' ) for city '$city' from city '$city' ..."
	
	cd $extDir
	sudo docker-compose -f "$city.yml" down
	cd ../../
	
	mv "$ymlFile" "$ymlFileInactive" --verbose
	if ! [ -f "$ymlFileInactive" ]; then
		redecho "   Removing failed! Do I have write access to '$ymlFile'?">&2
		exit 1
	fi
	blueecho "   This operation did not remove file '$ymlFile' but set it to 'inactive'!"
else
	greenecho "   extension '$extname' for city '$city' already removed. No need to do it again :)"
fi

removeNGINXconf() {
	if [ -f "./data/nginx/$1/$city/$extname.conf" ]; then
		orangeecho "   removing nginx configuration of extension '$extname' from nginx city config for '$city'  ..."
		rm "./data/nginx/$1/$city/$extname.conf" --verbose
	fi

	if [ -d "./data/nginx/$1/$city" ] && [ -z `dir "./data/nginx/$1/$city"` ]; then
		orangeecho "   removing nginx configuration of city '$city' because it's empty now ..."
		rm -R "./data/nginx/$1/$city" --verbose
		if [ -f "./data/nginx/$1/$city.conf" ]; then
			orangeecho "   completing removal of nginx configuration for city '$city' ..."
			rm "./data/nginx/$1/$city.conf" --verbose
		fi
	fi
}

blueecho "3. remove interweb nginx configuration"
removeNGINXconf "interweb"
if [ "$env" = "production" ]; then
	blueecho "4. remove intraweb nginx configuration"
	removeNGINXconf "intraweb"
fi

greenecho "removed trufi extension '$extname' from city '$city'"
