#!/bin/bash

projectname=`basename "$PWD"`

source ./lib/colorful

blueecho "performing some checks & normalizations ..."
source ./lib/validation

modulename="${args[0]}"
moduleDir="./modules/$modulename"
## if $modulename is empty or $moduleDir does not exist
if [ -z $modulename ] || ! [ -d "$moduleDir" ]; then
	redecho "  Error: You must specify a valid name of an module to add to city '$city'">&2
	echo "  A list of modules available:"
	dir ./modules
	exit 1
elif [ -f "$moduleDir/$city.yml.inactive" ]; then
	redecho "  Module '$modulename' inactive in city '$city'. Inactive modules cannot be restarted!"
	exit 1
fi

cd "$moduleDir"
sudo docker-compose -p "$projectname" -f "$city.yml" --env-file ../../$cityfile restart
cd ../../
