#!/bin/bash

projectname=`basename "$PWD"`

source ./lib/env
source ./lib/singlenv
source ./lib/colorful

orangeecho "This script has been deprecated and will be removed in the next major release v3.0.0"

blueecho "performing some checks & normalizations ..."
source ./lib/validation

modulename="${args[0]}"
moduleDir="./modules/$modulename"
## if $modulename is empty or $moduleDir does not exist
if [ -z $modulename ] || ! [ -d "$moduleDir" ]; then
	redecho "  Error: You must specify a valid name of an module to add to mandant '$mandant'">&2
	echo "  A list of modules available:"
	ls -p ./modules | grep -v /
	exit 1
elif [ -f "$moduleDir/$mandant.yml.inactive" ]; then
	redecho "  Module '$modulename' inactive in mandant '$mandant'. Inactive modules cannot be restarted!"
	exit 1
fi

cd "$moduleDir"
sudo $DOCKER_COMPOSE -f "$mandant.yml" --env-file ../../$mandantFile restart
cd ../../
