#!/bin/bash
source ./lib/env
source ./lib/singlenv
source ./lib/colorful
source ./lib/utils
source "lib/plugin"
# server [mandant] action [module] [actionargs]

# Run added modules (this will be automatically normalized to 'up --detach' before passing to docker-compose)
# ---------------------
# server run

# Stop added modules
# ---------------------
# server stop

# View running containers
# ---------------------
# server ls

# Restart added modules
# ---------------------
# server restart

# Shut down added modules
# ---------------------
# server down

# Pause added modules
# ---------------------
# server pause

# Unpause added modules
# ---------------------
# server unpause

# other commands that docker-compose accepts

# Initalize and validate
projectname=`basename "$PWD"`
args=( $@ )

declare -A mandantsPerModule

## if the first argument is a valid mandant configuration file and provided in the form 'name of mandant' or 'name of mandant.env'
## e.g.: server [mandant] action [module] [actionargs]
##               ....
envfile="${args[0]/'.env'/''}.env"
if [ -f "./config/$envfile" ]; then # export the variables in the mandant configuration file
	source ./config/$envfile
	blueecho "performing some checks & normalizations ..."
	source ./lib/validation # will re-init variable 'args' and will normalize it with self-provided function 'removeFirstElemInArgs'
	curMandant="$mandant" # only to provide analog behaviour to the comming 'curAction', 'curModule' and 'curActionArgs' variables but not needed for this architecture to work properly except for plugins using 'curMandant'
fi

if [ ${#args[@]} -eq 0 ]; then
	redecho "Error: Not enough arguments!"
	echo "USAGE: ./server [mandant] action [module] [actionargs]"
	echo ""
	echo "[mandant]         Optional, name of the mandant e.g. 'Bolivia-Cochabamba' or 'ITHouse'"
	echo "action         Required, name of the action to execute/perform e.g. 'start'"
	echo "[module]       Optional, name of the module to execute/perform action against e.g. 'tileserver'"
	echo "[actionargs]   Optional, additional arguments for the action to execute/perform e.g. '--build --detach' for action 'up'"
	exit 1
fi

## e.g.: server [mandant] action [module] [actionargs]
##                     ......
curAction="${args[0]}"
action="$curAction"
removeFirstElemInArgs
## e.g.: server [mandant] action [module] [actionargs]
##                            ........
#if [ -n "${args[0]}" ] && [ -d "./modules/${args[0]}" ]; then
curModule="${args[0]}"
removeFirstElemInArgs
#fi
## e.g.: server [mandant] action [module] [actionargs]
##                                     ............
curActionArgs="${args[@]}"

# Define the core

## batch execution (based on what an iterator has found previously)
performExecution() {
	if [ -z "${!mandantsPerModule[@]}" ]; then # a message for developers
		redecho "Trying to call 'performExecution' without running 'performIteration \"noexecute\"' before leads to this error message!"
		echo "crying ..."
		return
	
	fi
	for module in "${!mandantsPerModule[@]}"; do
		orangeecho "performing desired action '$curAction' on module '$module' ..."
		if [ -d "$module" ]; then
			local oldpwd="$PWD"
			cd "$module"

			local mandants=( ${mandantsPerModule[$module]} )
			for mandant in "${mandants[@]}"; do
				orangeecho "  - in mandant $mandant ..."
				if [ -n "$1" ]; then # assume a function when given
					"$@" "$module" "$mandant";
				else
					sudo $DOCKER_COMPOSE -p "${projectname}" -f "$mandant.yml" $curAction $curActionArgs
				fi
			done

			cd "$oldpwd"
		fi
	done
}

## iterators for modules
### perform on all mandants of a module
iterateThroughAllMandantsOfModule() {
	cd "modules/$1"
	addedMandants=""
	for composeFile in `ls | grep .yml`; do
		if ! [ "$composeFile" = "docker-compose.yml" ] && [[ "$composeFile" == *.yml ]] && [ -f "$composeFile" ]; then
			addedMandants+="${composeFile/'.yml'/''} "
		fi
	done
	if [ -n "$addedMandants" ]; then
		mandantsPerModule["modules/$1"]=$addedMandants
	fi
	cd "../../"
}

### perform on all modules in a mandant
iterateThroughAllModulesOfMandant() {
	cd modules
	for module in `ls -p ./ | grep /`; do
		module=${module/\//""}
		cd "$module"
		
		if [ -f "$1.yml" ]; then
			mandantsPerModule["modules/$module"]="$1"
		fi
		
		cd ../
	done
	cd ../
}

### perform on all modules in all mandants
iterateThroughEverything() {
	for module in `ls -p modules | grep /`; do
		local module=${module/\//""}
		iterateThroughAllMandantsOfModule $module $1
	done
}

### determine iteration strategy to use and call it
performIteration() {
	local error=""
	if [ -z "$curMandant" ] && [ -z "$curModule" ]; then # no mandant and no module have been specified (perform on all modules in all mandants)
		# server action
		iterateThroughEverything $1 # perform on all modules in all mandants
	elif [ -z "$curMandant" ] && [ -n "$curModule" ]; then # no mandant but a module have been specified
		# server action module [actionargs]
		iterateThroughAllMandantsOfModule $curModule $1 # perform on all mandants of a module
	elif [ -n "$curMandant" ] && [ -z "$curModule" ]; then # a mandant but no module have been specified
		# server mandant action
		iterateThroughAllModulesOfMandant $mandant $1 # perform on all modules in current mandant
	elif [ -n "$curMandant" ] && [ -n "$curModule" ]; then # a mandant and a module have been specified
		# server mandant action module [actionargs]
		mandantsPerModule["modules/$curModule"]="$mandant"
	else # if this else gets called then it means something is wrong with the code
		redecho "Error: Action '$curAction' couldn't be run as an iteration strategy to perform couldn't be found!"
		local error="ITERATIONSTRATEGYNOTFOUND"
	fi
	if [ "$1" = "execute" ] && [ -z "$error" ]; then
		local locargs=( $@ )
		unset locargs[0]
		locargs=( `echo "${locargs[@]}"` )
		performExecution ${locargs[@]}
	fi
}

## attention please prompt
attentionPrompt() {
	local reason="$1"
	local mandantrelatedtext=""
	if [ -z "$reason" ]; then
		reason="(no reason provided)"
	fi
	redecho "----------------------------------------"
	echo -e "The action '$curAction' asks for\033[1;m your approval\033[0;m before continuing! There must be a\033[0;31m dangerous situation\033[0;m it wants you to be aware of"
	echo -e "Reason: \033[0;34m${reason}\033[0;m"
	echo -e "\033[1;37mExecution details:\033[0;m"
	if [ -n "$curMandant" ]; then
		echo -e "Affected mandant: \033[0;34m${mandant}\033[0;m"
		echo -e "Scope: \033[0;34mmandant\033[0;m"
		local mandantrelatedtext=" ofn mandant '$mandant'"
	else
		echo -e "Affected mandant: \033[0;34m(action will be applied to all mandants when approving)\033[0;m"
		echo -e "Scope: \033[0;34mall\033[0;m"
	fi
	if [ -n "$curModule" ]; then
		echo -e "Affected module: \033[0;34m${curModule}\033[0;m"
	else
		echo -e "Affected module: \033[0;34m(action will be applied to all modules${mandantrelatedtext} when approving)\033[0;m"
	fi
	echo -e "Action: \033[0;34m${curAction}\033[0;m"
	echo -e "Action arguments: \033[0;34m${curActionArgs}\033[0;m"
	echo -e "Current date and time: \033[0;34m$(date)\033[0;m"
	redecho "----------------------------------------"
	
	decide() {
		echo -ne "\033[0;35mYour decision [y|n]:\033[0;m \033[0;34m"
		read decision
		if [ "$decision" = "n" ]; then
			greenecho "Action '$curAction' has been interrupted at your request. Nothing dangerous has been executed!"
			echo "Script interrupted by user"
			exit 2
		elif [ "$decision" = "y" ]; then
			orangeecho "Execution of action '$curAction' continues!"
			return
		else
			redecho "Invalid input. Only 'y' and 'n' (case-sensitive) counts!"
			decide
		fi
	}
	decide
}

# Call actions (made by plugins)
pluginargs=( ${moreargs[@]} )
invokeSinglePlugin "server" "$curAction"
if [ $pluginsInvoked -eq 1 ]; then # a plugin hasn't been invoked
	if [ "$curAction" = "down" ] || [ "$curAction" = "stop" ]; then
		attentionPrompt "Are you sure that nothing depends on the modules you want to perform action '$curAction' on?"
		performIteration "execute"
	else # no additional behaviour defined so pass to docker-compose directly
		performIteration "execute"
	fi
fi

# Detect and add plugins for chiefs (files in 'plugins/chief' ending in '.yml')
chief_plugins=""
for i in `ls plugins/chief | grep "\.yml$"`; do
	chief_plugins+=" -f plugins/chief/$i"
done

# Determine if there are still running services after certain action has been performed
## Difference between 'grep "${projectname}-chief"' and '-p "${projectname}"':
## grep "${projectname}-chief": This is a combination of the project name being the same for all modules and all chiefs running under this structure AND the prefix of the service names in the docker-compose.yml
## -p "${projectname}": This is the project name of the structure itself. It is being the same for all modules and all chiefs running under this structure
runningServices=`sudo docker container ls | grep "${projectname}" | wc -l` # count running services including the chief ones
allServiceContainers=`sudo docker container ls --all | grep "${projectname}" | wc -l` # count all services including the chief ones
runningChiefs=`sudo docker container ls | grep "${projectname}_chief-" | wc -l` # count running chiefs
allChiefContainers=`sudo docker container ls --all | grep "${projectname}_chief-" | wc -l`
allChiefsAvailable=`sudo $DOCKER_COMPOSE -f docker-compose.yml$chief_plugins config --services | wc -l` # count all chiefs
## if no service is running (except the chiefs)
if [ 0 -eq $((runningServices-runningChiefs)) ]; then
	### check if they have been removed completely (except the chiefs)
	if [ 0 -eq $((allServiceContainers-runningChiefs)) ]; then # also stop and remove all chiefs
		orangeecho "turning down chiefs as there are no docker containers left ..."
		sudo $DOCKER_COMPOSE -p "${projectname}" -f "docker-compose.yml"$chief_plugins down # so we can even turn down and remove the chief ones
	else ### not all services have been removed but they have been stopped (chiefs not counted in)
		orangeecho "stopping chiefs as there are only stopped containers ..."
		sudo $DOCKER_COMPOSE -p "${projectname}" -f "docker-compose.yml"$chief_plugins stop # so we just stop the chiefs
	fi
else ## if services are running (chiefs not counted in)
	### if amount of chiefs having containers is greater than the amount of running ones
	if [ $allChiefContainers -gt $runningChiefs ]; then
		orangeecho "start chiefs as there are running docker containers ..."
		sudo $DOCKER_COMPOSE -p "${projectname}" -f "docker-compose.yml"$chief_plugins start # start them all
	### if amount of chiefs (including ones without a container) is greater than the amount of existing chief containers
	elif [ $allChiefsAvailable -gt $allChiefContainers ]; then
		orangeecho "turning up chiefs as there are running docker containers ..."
		sudo $DOCKER_COMPOSE -p "${projectname}" -f "docker-compose.yml"$chief_plugins up --build --detach # wire up the missing chiefs
	fi
fi
