#!/bin/bash
# makes sense for production only

source ./lib/colorful

blueecho "performing some checks & normalizations ..."
source ./lib/validation

modulename="${args[0]}"
# remove elem on first index
unset args[0]
args=( `echo "${args[@]}"` )

containername="$modulename-$city"
moreargs="false"
projectname=`basename "$PWD"`

if [ -z "$modulename" ]; then
    echo 'Error: extension name as param is needed (e.g. "tileserver")' >&2
    exit 1
fi

if [ ${#args[@]} -gt 0 ]; then
	moreargs="true"
fi

if [ "$moreargs" = "false" ]; then
	args+=( --since today --follow )
fi

arguments="${args[@]}"

# determining right container name
containername="${projectname}_${containername}"
containername=`sudo docker container ls --format "{{.Names}}"`
containername=`echo $containername | grep $containername`

orangeecho "Executing 'sudo journalctl CONTAINER_NAME=\"${containername}\" $arguments'"
sudo journalctl CONTAINER_NAME="${containername}" $arguments
