#!/bin/bash

# colorful input
greenecho() {
	echo -e "\033[1;36m$1\033[0;m"
}

orangeecho() {
	echo -e "\033[1;33m$1\033[0;m"
}

redecho() {
	echo -e "\033[1;31m$1\033[0;m"
}

blueecho() {
	echo -e "\033[1;34m$1\033[0;m"
}
