#!/bin/bash

# Implements the following feature:
# If there is only one mandant configuration file ending with `.env` left then you can use the commands without the `<mandants' name>` argumente.g. `add_module tileserver` or `server up tileserver`. But as soon as there are more than one then you need to specify `<mandants' name>` of course.

determineAmountOfEnabledMandantConfigurationFiles() {
	# return the amount of available configuration files ending with '.env'
#                                                return all content of directory 'config'
#                                                          filter by all content having '.env' at the end ($)
#                                                                          count the filtered output
	local amountOfEnabledMandantConfigurationFiles=`ls config | grep "\.env$" | wc -l`
	if [ $amountOfEnabledMandantConfigurationFiles -eq 1 ]; then
		echo "$(tput blink)$(tput setaf 6)Only one mandant configuration file exists, enabling feature 'single environment' ...$(tput sgr0)"
		mandantFile="./config/`ls config | grep "\.env$"`"
		cityfile="$mandantFile"
	fi
}
determineAmountOfEnabledMandantConfigurationFiles