#!/bin/bash

# environment and mode
args=( $@ )
source ./lib/env

# validations

## if $cityfile is empty but a valid city configuration name has been provided
if [ -z "$cityfile" ] && [ -f "./config/${args[0]/".env"/""}.env" ]; then
	envname=${args[0]//".env"/""}
	export cityfile="./config/$envname.env"
	
	# remove elem on first index
	unset args[0]
	args=( `echo "${args[@]}"` )
fi

## if $cityfile contains something but the $city environment variable hasn't been populated
if [ -n "$cityfile" ] && [ -z "$city" ]; then
	orangeecho "  importing city file '$cityfile' ..."
	#. ./workon
	source ./$cityfile
fi

## if $city is empty
if [ -z "$city" ]; then
	redecho "  Error: Your config file at '$cityfile' hasn't been loaded correctly or is corrupted. Try executing '. ./workas' . Are you sure you specified the 'city' variable in that env file?">&2
fi
