#!/bin/bash

# environment and mode
args=( $@ )
source ./lib/env

# validations
## if $cityfile is empty and the user specified less than two arguments
if [ -z "$cityfile" ] && [ ${#args[@]} -lt 2 ]; then
	redecho "  Insufficient arguments.">&2
	usage
	exit 1
	
fi

## if $cityfile is empty but the user specified two arguments
if [ -z "$cityfile" ] && [ "${#args[@]}" = "2" ]; then
	envname=${args[0]//".env"/""}
	export cityfile="./config/$envname.env"
	unset args[0]
fi

## if $cityfile contains something but the $city environment variable hasn't been populated
if [ -n "$cityfile" ] && [ -z "$city" ]; then
	orangeecho "  invoke '. ./workon' ..."
	. ./workon
fi

## if $city is empty
if [ -z "$city" ]; then
	redecho "  Error: Your config file at '$cityfile' hasn't been loaded correctly or is corrupted. Try executing '. ./workas' . Are you sure you specified the 'city' variable in that env file?">&2
fi
